name = "chooseus"
pages_build_output_dir = "public"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "chooseus-db"
database_id = "5504320e-ae9e-4482-975a-9c66579298ba"
